### ISSUE TITLE
Tests don't work on Python 2.6

### ISSUE THREAD

**Issue by mgorny** [ojii/pymaging#36]
# 

```
ERROR: test_format_registration (pymaging.tests.test_basic.DrawTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mgorny/git/pymaging/pymaging/tests/test_basic.py", line 301, in test_format_registration
    self.assertIsInstance(img, Image)
AttributeError: 'DrawTests' object has no attribute 'assertIsInstance'

----------------------------------------------------------------------
```

The `assertIsInstance()` function is not available in Python 2.6. Possible solutions:
1. Use `unittest2.TestCase` as base class in Python 2.6,
2. Re-implement it in pymaging in Python 2.6,
3. Replace its use with `assertTrue(isinstance(...))` or something similar.

**Comment by ojii** [comment]
Thanks for reporting, fixed.
